Bugfix: wrongly assign gen_config with True  (#1594)
* Bugfix: fix bugs with error info:"
 if gen_config.stop_words is None:

AttributeError: 'bool' object has no attribute 'stop_words'",which is caused by assign gen_config with value 'True'.

* Style: Fix flake8 line length issue